### ISSUE TITLE
Component not re rendering when a rating value changes.

### ISSUE THREAD

**Issue by KamyarLajani** [rubenvar/svelte-star-rating#1]
I am facing this issue whenever a rating value changes, the StarRating component not re rendering and only shows the previous rating styles.
Example:
`<script>
let value = 1;
  setTimeout(() => {
    value = 3;
  }, 3000);
</script>
<StarRating rating={value}></StarRating>
`
I think you have to use reactive expression for the rating value inside your component. Thanks

**Comment by rubenvar** [comment]
Thanks for the suggestion @KamyarLajani

I originally created this package to use it on a side-project and didn't need this feature, but it shouldn't be too difficult to implement so I will try to find time and add it as soon as possible.

**Comment by rubenvar** [comment]
Hey @KamyarLajani the component is now reactive and the stars are re-rendering on value change, please test it and let me know if there is any problem.
