### ISSUE TITLE
Stars lose color if first component instance is hidden (display:none)

### ISSUE THREAD

**Issue by JulianZschieschang** [rubenvar/svelte-star-rating#2]
If the component is used multiple times, all stars lose their gradient as soon as the first component instance is set to display:none.

I made a minimal example: [REPL](https://svelte.dev/repl/daa4e1439cb749879d71bf9c79800fd2)
If you click the first button, all stars lose their color, but they are still there.
The other two don't impact the overall behaivor, as it should.

I am working on a solution.

**Comment by JulianZschieschang** [comment]
I just noticed I used **svelte-star-rating** instead of **svelte-stars-rating**. 
There is noch issue, sorry for the inconvenience.

**Comment by rubenvar** [comment]
🤷‍♂️
